spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/sport_manager?sslmode=require"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080

jwt:
  secret: "8fK29xLmQwPz91AaBcDeFgHiJkLmNoPqRsTuVwXyZ123456"
  access-expiration: 900000
  refresh-expiration: 2592000000
